parameters: {}
environment: {}
packages:
    - name: mka-northwest
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: send-sms
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          websecure: false
          parameters: {}
          environment: 
            MONGODB_USERNAME: "${MONGODB_USERNAME}"
            MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
            MONGODB_CLUSTER: "${MONGODB_CLUSTER}"
            TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
            TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
            TWILIO_SERVICE_SID: "${TWILIO_SERVICE_SID}"
          annotations: {}
          limits: {}
